/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package catalogapp;

/**
 *
 * @author My PC
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCardBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        viewCardBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        editCardBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        removeCardBtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addCardBtn.setBackground(new java.awt.Color(0, 51, 51));
        addCardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCardBtnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Catalog Card");

        javax.swing.GroupLayout addCardBtnLayout = new javax.swing.GroupLayout(addCardBtn);
        addCardBtn.setLayout(addCardBtnLayout);
        addCardBtnLayout.setHorizontalGroup(
            addCardBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCardBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        addCardBtnLayout.setVerticalGroup(
            addCardBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCardBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(addCardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, -1, -1));

        viewCardBtn.setBackground(new java.awt.Color(0, 51, 51));
        viewCardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewCardBtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("View Catalog Card");

        javax.swing.GroupLayout viewCardBtnLayout = new javax.swing.GroupLayout(viewCardBtn);
        viewCardBtn.setLayout(viewCardBtnLayout);
        viewCardBtnLayout.setHorizontalGroup(
            viewCardBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCardBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        viewCardBtnLayout.setVerticalGroup(
            viewCardBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCardBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(viewCardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 192, 187, -1));

        editCardBtn.setBackground(new java.awt.Color(0, 51, 51));
        editCardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCardBtnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Edit Catalog Card");

        javax.swing.GroupLayout editCardBtnLayout = new javax.swing.GroupLayout(editCardBtn);
        editCardBtn.setLayout(editCardBtnLayout);
        editCardBtnLayout.setHorizontalGroup(
            editCardBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCardBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        editCardBtnLayout.setVerticalGroup(
            editCardBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCardBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(editCardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 192, 186, -1));

        removeCardBtn.setBackground(new java.awt.Color(0, 51, 51));
        removeCardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeCardBtnMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Remove Catalog Card");

        javax.swing.GroupLayout removeCardBtnLayout = new javax.swing.GroupLayout(removeCardBtn);
        removeCardBtn.setLayout(removeCardBtnLayout);
        removeCardBtnLayout.setHorizontalGroup(
            removeCardBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeCardBtnLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        removeCardBtnLayout.setVerticalGroup(
            removeCardBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeCardBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(removeCardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 60, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 80, 80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCardBtnMouseClicked
        AddCatalogCard AddCard = new AddCatalogCard();
        AddCard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addCardBtnMouseClicked

    private void removeCardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCardBtnMouseClicked
        RemoveCatalogCard RemoveCard = new RemoveCatalogCard();
        RemoveCard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_removeCardBtnMouseClicked

    private void editCardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCardBtnMouseClicked
        EditCatalogCard EditCard = new EditCatalogCard();
        EditCard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editCardBtnMouseClicked

    private void viewCardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewCardBtnMouseClicked
        ViewCatalogCard ViewCard = new ViewCatalogCard();
        ViewCard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewCardBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addCardBtn;
    private javax.swing.JPanel editCardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel removeCardBtn;
    private javax.swing.JPanel viewCardBtn;
    // End of variables declaration//GEN-END:variables
}
